@startuml
class "SeatingMapProvider" as SMP {
  +venue : Object
  +selectedSeatId : UUID
  --
}

class "SeatingMap" as SM {
  +background? : String
  +height : Number
  +width : Number
  +svgData : String
  --
  +renderNodeChild(node : Node) : Function
}

class "VirtualMap" as VM {
  +withRotation? : Boolean
  +width : Number
  +baseWidth : Number
  +height : Number
  +baseHeight : Number
  +minScaleFactor? : Number
  +maxScaleFactor? : Number
  --
  +handeZoomAction(scale : Number) : Function
}

class "SeatSheet" as Sheet {
    +seatConfiguration? : Object
    --
}

class "Seat" as Seat {
  +seat : Object
}

SMP -> SM
SM --> VM
SM -> Sheet
VM -> Seat

@enduml
